version: "3.7"

services:
  backend-mongo:
    image: mongo:4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=backend
      - MONGO_INITDB_ROOT_PASSWORD=security
    volumes:
      - ./.db-data/backend-db:/data/db
    ports:
      - 27020:27017
  backend:
    container_name: backend-service
    build: ./backend
    working_dir: /home/node/app
    depends_on:
      - backend-mongo
    environment:
      - NODE_ENV=development
    ports:
      - 8080:4000
    volumes:
      - ./backend/src:/home/node/app/src
    command: bash -c "npm start"
